apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fyle
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
