apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
  namespace: alma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: react-webapp
          image: 660829820053.dkr.ecr.ap-south-1.amazonaws.com/alma-react:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
